function saveLog(folderName, photoFilename, category, _posture, pose) {
  console.log("save " + category + " log");
  //save the log file to the disk
  const fs = require('fs');
  var csvWriter = require('csv-write-stream');
  var writer = csvWriter({ sendHeaders: false }); //Instantiate var
  var csvFilename = folderName + "poseture_log.csv";
  // If CSV file does not exist, create it and add the headers
  if (!fs.existsSync(csvFilename)) {
    writer = csvWriter({ sendHeaders: false });
    writer.pipe(fs.createWriteStream(csvFilename));
    writer.write({
      header0_0: 'date',
      header0_1: 'photo',
      header0_2: 'category',
      header0_3: 'posture',
      header1_1: 'nose_score',
      header1_2: 'nose_position_x',
      header1_3: 'nose_position_y',
      header2_1: 'leftEye_score',
      header2_2: 'leftEye_position_x',
      header2_3: 'leftEye_position_y',
      header3_1: 'rightEye_score',
      header3_2: 'rightEye_position_x',
      header3_3: 'rightEye_position_y',
      header4_1: 'leftEar_score',
      header4_2: 'leftEar_position_x',
      header4_3: 'leftEar_position_y',
      header5_1: 'rightEar_score',
      header5_2: 'rightEar_position_x',
      header5_3: 'rightEar_position_y',
      header6_1: 'leftShoulder_score',
      header6_2: 'leftShoulder_position_x',
      header6_3: 'leftShoulder_position_y',
      header7_1: 'rightShoulder_score',
      header7_2: 'rightShoulder_position_x',
      header7_3: 'rightShoulder_position_y',
      header8_1: 'leftElbow_score',
      header8_2: 'leftElbow_position_x',
      header8_3: 'leftElbow_position_y',
      header9_1: 'rightElbow_score',
      header9_2: 'rightElbow_position_x',
      header9_3: 'rightElbow_position_y',
      header10_1: 'leftWrist_score',
      header10_2: 'leftWrist_position_x',
      header10_3: 'leftWrist_position_y',
      header11_1: 'rightWrist_score',
      header11_2: 'rightWrist_position_x',
      header11_3: 'rightWrist_position_y',
      header12_1: 'leftHip_score',
      header12_2: 'leftHip_position_x',
      header12_3: 'leftHip_position_y',
      header13_1: 'rightHip_score',
      header13_2: 'rightHip_position_x',
      header13_3: 'rightHip_position_y',
      header14_1: 'leftKnee_score',
      header14_2: 'leftKnee_position_x',
      header14_3: 'leftKnee_position_y',
      header15_1: 'rightKnee_score',
      header15_2: 'rightKnee_position_x',
      header15_3: 'rightKnee_position_y',
      header16_1: 'leftAnkle_score',
      header16_2: 'leftAnkle_position_x',
      header16_3: 'leftAnkle_position_y',
      header17_1: 'rightAnkle_score',
      header17_2: 'rightAnkle_position_x',
      header17_3: 'rightAnkle_position_y',
    });
    writer.end();
  }
  // Append some data to CSV the file    
  writer = csvWriter({ sendHeaders: false });
  writer.pipe(fs.createWriteStream(csvFilename, { flags: 'a' }));
  let date = new Date();
  let dateString = date.toLocaleDateString() + " " + date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds();
  writer.write({
    header0_0: dateString,
    header0_1: photoFilename,
    header0_2: category,
    header0_3: _posture,
    header1_1: pose.keypoints[0].score,
    header1_2: pose.keypoints[0].position.x,
    header1_3: pose.keypoints[0].position.y,
    header2_1: pose.keypoints[1].score,
    header2_2: pose.keypoints[1].position.x,
    header2_3: pose.keypoints[1].position.y,
    header3_1: pose.keypoints[2].score,
    header3_2: pose.keypoints[2].position.x,
    header3_3: pose.keypoints[2].position.y,
    header4_1: pose.keypoints[3].score,
    header4_2: pose.keypoints[3].position.x,
    header4_3: pose.keypoints[3].position.y,
    header5_1: pose.keypoints[4].score,
    header5_2: pose.keypoints[4].position.x,
    header5_3: pose.keypoints[4].position.y,
    header6_1: pose.keypoints[5].score,
    header6_2: pose.keypoints[5].position.x,
    header6_3: pose.keypoints[5].position.y,
    header7_1: pose.keypoints[6].score,
    header7_2: pose.keypoints[6].position.x,
    header7_3: pose.keypoints[6].position.y,
    header8_1: pose.keypoints[7].score,
    header8_2: pose.keypoints[7].position.x,
    header8_3: pose.keypoints[7].position.y,
    header9_1: pose.keypoints[8].score,
    header9_2: pose.keypoints[8].position.x,
    header9_3: pose.keypoints[8].position.y,
    header10_1: pose.keypoints[9].score,
    header10_2: pose.keypoints[9].position.x,
    header10_3: pose.keypoints[9].position.y,
    header11_1: pose.keypoints[10].score,
    header11_2: pose.keypoints[10].position.x,
    header11_3: pose.keypoints[10].position.y,
    header12_1: pose.keypoints[11].score,
    header12_2: pose.keypoints[11].position.x,
    header12_3: pose.keypoints[11].position.y,
    header13_1: pose.keypoints[12].score,
    header13_2: pose.keypoints[12].position.x,
    header13_3: pose.keypoints[12].position.y,
    header14_1: pose.keypoints[13].score,
    header14_2: pose.keypoints[13].position.x,
    header14_3: pose.keypoints[13].position.y,
    header15_1: pose.keypoints[14].score,
    header15_2: pose.keypoints[14].position.x,
    header15_3: pose.keypoints[14].position.y,
    header16_1: pose.keypoints[15].score,
    header16_2: pose.keypoints[15].position.x,
    header16_3: pose.keypoints[15].position.y,
    header17_1: pose.keypoints[16].score,
    header17_2: pose.keypoints[16].position.x,
    header17_3: pose.keypoints[16].position.y,
  });
  writer.end();
}
exports.saveLog = saveLog;
